services:
  postgres:
    image: pgvector/pgvector:pg17

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

    ports:
      - "8501:8501"

    depends_on:
      - postgres
    
    volumes:
      - model_cache:/root/.cache/huggingface

volumes:
  postgres_data:
  model_cache: